#!/bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure)
        rm -f /etc/dconf/db/ibus
        dconf update
	;;
    failed-upgrade)
	;;
    *)
	echo "prerm called with unknown argument \`$1'" >&2
	exit 1
   ;;
esac


# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p ibus 
else
	dpkg -L ibus | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section


exit 0
