#!/bin/sh
set -e

case "$1" in
    configure)
	rm -f /etc/xdg/autostart/ibus.desktop
        rm -f /etc/dconf/db/ibus
        dconf update
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p ibus /usr/share/ibus
fi

# End automatically added section



