#!/bin/sh

set -e

dpkg-maintscript-helper mv_conffile /etc/php5/fpm/main.conf /etc/php5/fpm/php-fpm.conf 5.3.5-1 -- "$@"

# Automatically added by dh_installinit
if [ "$1" = install ] || [ "$1" = upgrade ]; then
	if [ -e "/etc/init.d/php5-fpm" ] && [ -L "/etc/init.d/php5-fpm" ] \
	   && [ $(readlink -f "/etc/init.d/php5-fpm") = /lib/init/upstart-job ]
	then
		rm -f "/etc/init.d/php5-fpm"
	fi
fi
# End automatically added section


exit 0
