name: Build and Release Custom ISO

on:
  release:
    types: [created]

jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y squashfs-tools genisoimage

      - name: Create filesystem.squashfs from unpacked root
        run: |
          mkdir -p iso-root/casper
          sudo mksquashfs squashfs-root iso-root/casper/filesystem.squashfs -noappend -always-use-fragments

      - name: (Optional) Update MD5 Hashes
        run: |
          cd iso-root
          rm -f md5sum.txt
          find . -type f -print0 | xargs -0 md5sum > md5sum.txt
          sed -i '/md5sum.txt/d' md5sum.txt
          cd ..

      - name: Generate ISO Filename
        run: echo "iso_name=darkly-${{ github.ref_name }}.iso" >> $GITHUB_ENV

      - name: Build the bootable ISO
        run: |
          mkisofs -r -J -b isolinux/isolinux.bin -c isolinux/boot.cat \
          -no-emul-boot -boot-load-size 4 -boot-info-table \
          -o ${{ env.iso_name }} iso-root/

      - name: Upload ISO to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ env.iso_name }}
          asset_name: ${{ env.iso_name }}
          asset_content_type: application/x-iso9660-image
